name: Generate Sitemap

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1.10.1
